import { default as NextHead } from "next/head";
import React from "react";

interface HeadProps {
  title?: string;
}

const Head = (props: HeadProps) => {
  return (
    <NextHead>
      <title key="title">MrCoolTheCucumber</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <style
        dangerouslySetInnerHTML={{
          __html: `
            @import url('https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap');
            @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');
        `,
        }}
      />
    </NextHead>
  );
};

export default Head;
